# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using aws s3
name: Mood AWS Development Deployment
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+'
  workflow_dispatch:

# permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  build-n-deploy:
    uses: Mood-APIs/shared-workflows/.github/workflows/aws-development.yaml@main
    with:
      function-name: ${{ vars.FUNCTION_NAME }}
      tag: dev
      role-to-assume: ${{ vars.ROLE_TO_ASSUME }}
      region: ${{ vars.REGION }}
    secrets:
      account-id: ${{ secrets.ACCOUNT_ID }}
